### ISSUE TITLE
review theo NTO

### ISSUE THREAD

**Issue by Anto824** [kappablanka/OOP_atelier1_theoPiacentini#1]
*** DE ***

impossible d'avoir un dé à memoire avec un nom choisi, ou un nombre de faces choisi
https://github.com/kappablanka/OOP_atelier1_theoPiacentini/blob/eafc4d53f113be62bed16e1bbe5c1843cb8c5b4d/src/Exercice1/DesMemoire.java#L12

pareil ici
https://github.com/kappablanka/OOP_atelier1_theoPiacentini/blob/eafc4d53f113be62bed16e1bbe5c1843cb8c5b4d/src/Exercice1/DesAFaceAutres.java#L12

***  Entier  ***
addition faite 1 fois de trop, 
n = entier+pas;
if n<bornsup;
entier = n;
https://github.com/kappablanka/OOP_atelier1_theoPiacentini/blob/eafc4d53f113be62bed16e1bbe5c1843cb8c5b4d/src/Exercice2/Entier.java#L60

**Comment by kappablanka** [comment]
Tout à été corrigé
