### ISSUE TITLE
Des.java

### ISSUE THREAD

**Issue by dodcraft** [kappablanka/OOP_atelier1_theoPiacentini#2]
il te manque le constructeur(int nbfaces ,string nom) qui t'aurait permis de le reutiliser pour tes autres constructeurs
https://github.com/kappablanka/OOP_atelier1_theoPiacentini/blob/eafc4d53f113be62bed16e1bbe5c1843cb8c5b4d/src/Exercice1/Des.java#L44
inutile
https://github.com/kappablanka/OOP_atelier1_theoPiacentini/blob/eafc4d53f113be62bed16e1bbe5c1843cb8c5b4d/src/Exercice1/Des.java#L117
if(object!=null && instance of Class ) aurait été preferable
https://github.com/kappablanka/OOP_atelier1_theoPiacentini/blob/eafc4d53f113be62bed16e1bbe5c1843cb8c5b4d/src/Exercice1/Des.java#L107

**Comment by kappablanka** [comment]
Tout à été corrigé sauf la méthode equals que je pense plus précise.
