### ISSUE TITLE
DeAutre.java

### ISSUE THREAD

**Issue by dodcraft** [kappablanka/OOP_atelier1_theoPiacentini#3]
pas de modificateur d'acces et j'aurais fais une constante
https://github.com/kappablanka/OOP_atelier1_theoPiacentini/blob/eafc4d53f113be62bed16e1bbe5c1843cb8c5b4d/src/Exercice1/DesAFaceAutres.java#L7
j'aurais redefinis toSTring au lieu de creer une nouvelle fonction
https://github.com/kappablanka/OOP_atelier1_theoPiacentini/blob/eafc4d53f113be62bed16e1bbe5c1843cb8c5b4d/src/Exercice1/DesAFaceAutres.java#L19

**Comment by kappablanka** [comment]
Le problème 1 est réglé.

La méthodelanceFaceAutre() n'est pas une méthode d'affichage de l'objet
