### ISSUE TITLE
Entier.java

### ISSUE THREAD

**Issue by dodcraft** [kappablanka/OOP_atelier1_theoPiacentini#4]
j'aurais utilisé des constante pour les deux borne
https://github.com/kappablanka/OOP_atelier1_theoPiacentini/blob/eafc4d53f113be62bed16e1bbe5c1843cb8c5b4d/src/Exercice2/Entier.java#L8
il te manque le constructeur avec la valeur par defaut=0 et ta condtion pour les borne peut se faire en une ligne 
https://github.com/kappablanka/OOP_atelier1_theoPiacentini/blob/eafc4d53f113be62bed16e1bbe5c1843cb8c5b4d/src/Exercice2/Entier.java#L16

**Comment by kappablanka** [comment]
Problème 1 réglé.

La valeur par défaut à 0 pose problème comme indiqué par Mme. Nivet jeudi dernier.
